### ISSUE TITLE
Default hotkey for OS X

### ISSUE THREAD

**Issue by faergeek** [lnikell/css-converter#1]
Why don't you set default hotkey for OS X to `command+v`?

**Comment by lnikell** [comment]
Thank you! I forgot it. I will fix it tonight.

**Comment by faergeek** [comment]
I could make a PR.
Actually I thought about a few other improvements for this plugin.

**Comment by lnikell** [comment]
I would very apreciate if you help me improve the plugin. I have some ideas too, but don't have enough time. Currently I'm working on unprefix function of the plugin. This process going slow for me because I'm not a Python developer.

**Comment by faergeek** [comment]
So am I. I'm a JS developer :-)
But I'll try it out.

Is it necessary feature that it does not depend on third party packages?

I think it will be too hard to unprefix properties without postcss or something like that (properties may have different names when prefixed/unprefixed and also different formats).

Actually, we could just use autoprefixer to remove prefixes.

**Comment by lnikell** [comment]
You could add me at skype , and I will tell you some things about this plugin.
skype: lnikell
