### ISSUE TITLE
Trailing comma in Default (OSX).sublime-keymap throws error

### ISSUE THREAD

**Issue by skipzero** [lnikell/css-converter#12]
Just an annoying warning in sublime 2. 
Just need to remove comma here and don't wanna fork and do a pull request for a silly fix.
https://github.com/lnikell/css-converter/blob/master/Default%20(OSX).sublime-keymap#L2

**Comment by lnikell** [comment]
@zerosquadron Thank you for feedback. I will fix it at the weekend.
