### ISSUE TITLE
base 64encode bag

### ISSUE THREAD

**Issue by retyui** [lnikell/css-converter#14]
copy 

```
cursor url('data:image/png;base64,iVBORw0KGg...')
```

result paste

```
cursor url('data:image/pngbase64,iVBORw0KGg...')
```

bag: png;base64
-----------↑

**Comment by Kristinita** [comment]
+1

**Comment by Kristinita** [comment]
@retyui , why you close issue? This bug fix for you?

Thanks.

**Comment by retyui** [comment]
No(
This repo dead . 
I used alternative service:
http://css2sass.herokuapp.com
