### ISSUE TITLE
Option for leaving away colons (not semicolons)

### ISSUE THREAD

**Issue by TimOetting** [lnikell/css-converter#15]
In stylus, you don't even need the colons in between the key and values. So

``` stylus
body
  background red
  padding 30px
```

would be valid code. It would be nice if you could add an option to turn them of in the converted code.

**Comment by lnikell** [comment]
@TimOetting Hi, Tim! Css converter already have that option https://github.com/lnikell/css-converter#configuration-options you neec just to set it to false

**Comment by TimOetting** [comment]
Ah ok. You should then consider not to write about semicolons in the readme. 
Anyway, thanks for the plugin!
