### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by faergeek** [lnikell/css-converter#3]
Few points:
- I think it doesn't make sense to remove/replace colon at all if it's sass file.
- Setting custom string to replace colon is weird, so it should be boolean.
- Also it's spelled incorrectly, it's colon, not semicolon.
- Ideally we should get indentation and eol from view.
- And finally I guess there's no need for option prefixing as they are in separate file (not so sure, though).

So I think config should look something like this:

``` json
{
  "stylus_colon": true
}
```

What do you think about it?

**Comment by lnikell** [comment]
1. Agree
2. Agree, but I think name of option "colon" will be more good then "stylus_colon"
3. It will be good
