### ISSUE TITLE
Support for scss

### ISSUE THREAD

**Issue by PixelT** [lnikell/css-converter#4]
Add support for scss syntax

**Comment by lnikell** [comment]
Thank you for feedback. I will try to make it, but it is not a priority task, because scss support css syntax by default.

**Comment by faergeek** [comment]
@lnikell, it seems like that problem is introduced by my PR yesterday. `scss` is detected like `sass` too.
Will try to fix it.

**Comment by faergeek** [comment]
Sad, but I think we should revert my commit 2b3c231e4a93ce5ccc83f82babb7d0edfc8bf8e2
Sass package does not see any difference between sass and scss.

**Comment by lnikell** [comment]
@faergeek Not think so. We could use your way of defining file type when we dont have a file, when we hit ctrl + n for example. And  we could check  that it end on "sass" or "stylus" if file already exist

**Comment by faergeek** [comment]
Makes sense :+1: There's no way to distinguish `scss` and `sass` if we don't have a file anyway :-)

**Comment by lnikell** [comment]
I reverted commit. I will think about it at this weekend.

**Comment by faergeek** [comment]
@PixelT @lnikell Could you check if it's resolved?

**Comment by erralb** [comment]
Hi, for me it's not working with scss files... is it not supposed to work with them?
